# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y_gRJDzkTvmqky8mgTJY9tcimImF-ado
"""

import tensorflow as tf
from tensorflow import keras
import numpy as np
from keras.layers import Input, Conv2D, Dense, MaxPool2D, Concatenate, BatchNormalization, UpSampling2D
from keras.applications.vgg16 import VGG16
from keras import Model

def upconv(n1, n2, f):
    x = Conv2D(n1, (1, 1), activation = "relu", padding = "same")(f)
    x = BatchNormalization()(x)
    x = Conv2D(n2, (3, 3), activation = "relu", padding = "same")(x)
    x = BatchNormalization()(x)
    return upsample(x)

def upsample(x):
    x = UpSampling2D((2, 2), interpolation = "bilinear")(x)
    return x;

vgg16 = VGG16(
    include_top=False,
    weights="imagenet",
    input_shape=(512, 512, 3),
)

vgg16.trainable = False

stage5 = vgg16.get_layer('block5_conv3').output

s61 = Conv2D(512, (3, 3), activation = "relu", padding = "same")(stage5)
s62 = Conv2D(512, (3, 3), activation = "relu", padding = "same")(s61)
stage6 = Conv2D(512, (3, 3), activation = "relu", padding = "same")(s62)

u10 = Concatenate()([stage5, stage6])
up1 = upconv(512, 256, u10)
# u11 = Conv2D(512, (1, 1), activation = "relu", padding = "same")(u10)
# u12 = BatchNormalization()(u11)
# u13 = Conv2D(256, (3, 3), activation = "relu", padding = "same")(u12)
# u14 = BatchNormalization()(u13)
# up1 = UpSampling2D((2, 2), interpolation = "bilinear")(u14)

u20 = Concatenate()([up1, vgg16.get_layer('block4_conv3').output])
# u21 = Conv2D(256, (1, 1), activation = "relu", padding = "same")(u20)
# u22 = BatchNormalization()(u21)
# u23 = Conv2D(128, (3, 3), activation = "relu", padding = "same")(u22)
# u24 = BatchNormalization()(u23)
# up2 = UpSampling2D((2, 2), interpolation = "bilinear")(u24)
up2 = upconv(256, 128, u20)

u30 = Concatenate()([up2, vgg16.get_layer('block3_conv3').output])
# u31 = Conv2D(128, (1, 1), activation = "relu", padding = "same")(u30)
# u32 = BatchNormalization()(u31)
# u33 = Conv2D(64, (3, 3), activation = "relu", padding = "same")(u32)
# u34 = BatchNormalization()(u33)
# up3 = UpSampling2D((2, 2), interpolation = "bilinear")(u34)
up3 = upconv(128, 64, u30)

u40 = Concatenate()([up3, vgg16.get_layer('block2_conv2').output])
# u41 = Conv2D(64, (1, 1), activation = "relu", padding = "same")(u40)
# u42 = BatchNormalization()(u41)
# u43 = Conv2D(32, (3, 3), activation = "relu", padding = "same")(u42)
# u44 = BatchNormalization()(u43)
# up4 = UpSampling2D((2, 2), interpolation = "bilinear")(u44)
up4 = upconv(64, 32, u40)

ra1 = Conv2D(32, (3, 3), activation = "relu", padding = "same")(up4)
ra2 = Conv2D(32, (3, 3), activation = "relu", padding = "same")(ra1)
ra3 = Conv2D(16, (3, 3), activation = "relu", padding = "same")(ra2)
ra4 = Conv2D(16, (3, 3), activation = "relu", padding = "same")(ra3)

region = Conv2D(1, (1, 1), activation = "sigmoid", padding = "same")(ra4)
affinity = Conv2D(1, (1, 1), activation = "sigmoid", padding = "same")(ra4)

model = Model(inputs = vgg16.input, outputs=[region, affinity])
model.summary()

# s11 = Conv2D(64, (3, 3), activation = "relu", padding = "same")(inputs)
# s12 = Conv2D(64, (3, 3), activation = "relu", padding = "same")(s11)
# stage1 = MaxPool2D((2, 2))(s12)

# s21 = Conv2D(128, (3, 3), activation = "relu", padding = "same")(stage1)
# s22 = Conv2D(128, (3, 3), activation = "relu", padding = "same")(s21)
# stage2 = MaxPool2D((2, 2))(s22)

# s31 = Conv2D(256, (3, 3), activation = "relu", padding = "same")(stage2)
# s32 = Conv2D(256, (3, 3), activation = "relu", padding = "same")(s31)
# s33 = Conv2D(256, (3, 3), activation = "relu", padding = "same")(s32)
# stage3 = MaxPool2D((2, 2))(s33)

# s41 = Conv2D(512, (3, 3), activation = "relu", padding = "same")(stage3)
# s42 = Conv2D(512, (3, 3), activation = "relu", padding = "same")(s41)
# s43 = Conv2D(512, (3, 3), activation = "relu", padding = "same")(s42)
# stage4 = MaxPool2D((2, 2))(s43)

# s51 = Conv2D(512, (3, 3), activation = "relu", padding = "same")(stage4)
# s52 = Conv2D(512, (3, 3), activation = "relu", padding = "same")(s51)
# s53 = Conv2D(512, (3, 3), activation = "relu", padding = "same")(s52)
# stage5 = MaxPool2D((2, 2))(s53)

# model = keras.Model(inputs = inputs, outputs = [region, affinity])
# model = keras.Model(inputs = inputs, outputs = x)
# model.summary()

